// lib/helpers/questions.dart
const List<String> questionsPool = [
  "What's something that made you smile today?",
  "What are you grateful for right now?",
  "Describe your current mood in one word.",
  "What's been on your mind lately?",
  "Is there something you're avoiding?",
  "What energized you today?",
  "What drained you today?",
  "What do you need more of?",
  "What do you need less of?",
  "What's one thing you're proud of?",
  "How does your body feel right now?",
  "What's been weighing on you lately?",
  "Did you feel loved today? Why or why not?",
  "What moment today felt most alive?",
  "What have you recently learned about yourself?",
  "If you could redo today, what would you change?",
  "What habit has been helping you lately?",
  "What are you currently working on internally?",
  "What's your main focus today?",
  "What are you trying to move toward right now?",
  "What small thing could make today better?",
  "Do you feel aligned with your values today?",
  "What thought do you wish you could let go of?",
  "Who inspired you recently?",
  "What's a meaningful interaction you had this week?",
  "What's something you wish you could say to someone?",
  "Did someone make your day better today?",
  "Have you felt understood lately?",
  "What would a perfect day look like for you?",
  "If you could be anywhere right now, where would you be?",
  "What feeling do you want more of in your life?",
  "What kind of energy are you hoping to attract?",
  "What do you hope tomorrow brings?",
  "Where in your life are you feeling resistance?",
  "How would you describe your inner world today?",
  "What's been hard to accept lately?",
  "What helps you keep going?",
  "What truth about yourself are you starting to accept?",
];
