import 'package:flutter/material.dart';

const Map<String, Map<String, dynamic>> emotionColors = {
  "admiration": {"color": Color(0xFFA569BD), "name": "wisteria"},
  "amusement": {"color": Color(0xFFF39C12), "name": "buttercup"},
  "anger": {"color": Color(0xFFE74C3C), "name": "cinnabar"},
  "annoyance": {"color": Color(0xFFA04000), "name": "oregon"},
  "approval": {"color": Color(0xFF27AE60), "name": "jungle green"},
  "caring": {"color": Color(0xFFF1948A), "name": "apricot"},
  "confusion": {"color": Color(0xFF7D3C98), "name": "vivid violet"},
  "curiosity": {"color": Color(0xFFF4D03F), "name": "saffron"},
  "desire": {"color": Color(0xFFC0392B), "name": "tall poppy"},
  "disappointment": {"color": Color(0xFFD35400), "name": "burnt orange"},
  "disapproval": {"color": Color(0xFF6E2C00), "name": "nutmeg wood finish"},
  "disgust": {"color": Color(0xFF145A32), "name": "parsley"},
  "embarrassment": {"color": Color(0xFFF5B7B1), "name": "mandys pink"},
  "excitement": {"color": Color(0xFFE67E22), "name": "zest"},
  "fear": {"color": Color(0xFF34495E), "name": "pickled bluewood"},
  "gratitude": {"color": Color(0xFF52BE80), "name": "ocean green pearl"},
  "grief": {"color": Color(0xFF000000), "name": "black"},
  "joy": {"color": Color(0xFFF7DC6F), "name": "orange yellow"},
  "love": {"color": Color(0xFFEA6153), "name": "burnt sienna"},
  "nervousness": {"color": Color(0xFFD68910), "name": "meteor"},
  "optimism": {"color": Color(0xFF58D68D), "name": "caribbean green pearl"},
  "pride": {"color": Color(0xFF2874A6), "name": "jelly bean"},
  "realization": {"color": Color(0xFFBB8FCE), "name": "east side"},
  "relief": {"color": Color(0xFF82E0AA), "name": "algae green"},
  "remorse": {"color": Color(0xFF922B21), "name": "old brick"},
  "sadness": {"color": Color(0xFF1F6DA0), "name": "matisse"},
  "surprise": {"color": Color(0xFFF9E79F), "name": "marzipan"},
  "neutral": {"color": Color(0xFFBDC3C7), "name": "silver sand"},
};
